export const FLIGHTS = [
  {
    airlineLogo: 'https://voopter.com.br/voopter-static-assets/airline-logos/G3.png',
    price: '1.230',
    outbound: {
      day: '20/JAN',
      weekName: 'DOM',
      departureTime: '16:30',
      arrivalTime: '18:30',
      duretion: '2h',
    },
    back: {
      day: '22/JAN',
      weekName: 'TER',
      departureTime: '13:30',
      arrivalTime: '15:30',
      duretion: '2h',
    },
    departureAirport: 'FLN',
    arrivalAirport: 'GRU',
    id: '123',
  },
  {
    airlineLogo: 'https://voopter.com.br/voopter-static-assets/airline-logos/JJ.png',
    price: '1.230',
    outbound: {
      day: '20/JAN',
      weekName: 'DOM',
      departureTime: '16:30',
      arrivalTime: '18:30',
      duretion: '2h',
    },
    back: {
      day: '22/JAN',
      weekName: 'TER',
      departureTime: '13:30',
      arrivalTime: '15:30',
      duretion: '2h',
    },
    departureAirport: 'FLN',
    arrivalAirport: 'GRU',
    id: '4356',
  },
  {
    airlineLogo: 'https://voopter.com.br/voopter-static-assets/airline-logos/G3.png',
    price: '1.230',
    outbound: {
      day: '20/JAN',
      weekName: 'DOM',
      departureTime: '16:30',
      arrivalTime: '18:30',
      duretion: '2h',
    },
    back: {
      day: '22/JAN',
      weekName: 'TER',
      departureTime: '13:30',
      arrivalTime: '15:30',
      duretion: '2h',
    },
    departureAirport: 'FLN',
    arrivalAirport: 'GRU',
    id: '789',
  },
  {
    airlineLogo: 'https://voopter.com.br/voopter-static-assets/airline-logos/G3.png',
    price: '1.230',
    outbound: {
      day: '20/JAN',
      weekName: 'DOM',
      departureTime: '16:30',
      arrivalTime: '18:30',
      duretion: '2h',
    },
    back: {
      day: '22/JAN',
      weekName: 'TER',
      departureTime: '13:30',
      arrivalTime: '15:30',
      duretion: '2h',
    },
    departureAirport: 'FLN',
    arrivalAirport: 'GRU',
    id: '890',
  },
  {
    airlineLogo: 'https://voopter.com.br/voopter-static-assets/airline-logos/G3.png',
    price: '1.230',
    outbound: {
      day: '20/JAN',
      weekName: 'DOM',
      departureTime: '16:30',
      arrivalTime: '18:30',
      duretion: '2h',
    },
    back: {
      day: '22/JAN',
      weekName: 'TER',
      departureTime: '13:30',
      arrivalTime: '15:30',
      duretion: '2h',
    },
    departureAirport: 'FLN',
    arrivalAirport: 'GRU',
    id: '42334',
  },
  {
    airlineLogo: 'https://voopter.com.br/voopter-static-assets/airline-logos/G3.png',
    price: '1.230',
    departureAirport: 'FLN',
    arrivalAirport: 'GRU',
    id: '22333',
    outbound: {
      day: '20/JAN',
      weekName: 'DOM',
      departureTime: '16:30',
      arrivalTime: '18:30',
      duretion: '2h',
    },
    back: {
      day: '22/JAN',
      weekName: 'TER',
      departureTime: '13:30',
      arrivalTime: '15:30',
      duretion: '2h',
    },
  },
  {
    airlineLogo: 'https://voopter.com.br/voopter-static-assets/airline-logos/G3.png',
    price: '1.230',
    outbound: {
      day: '20/JAN',
      weekName: 'DOM',
      departureTime: '16:30',
      arrivalTime: '18:30',
      duretion: '2h',
    },
    back: {
      day: '22/JAN',
      weekName: 'TER',
      departureTime: '13:30',
      arrivalTime: '15:30',
      duretion: '2h',
    },
    departureAirport: 'FLN',
    arrivalAirport: 'GRU',
    id: '2342342',
  },
  {
    airlineLogo: 'https://voopter.com.br/voopter-static-assets/airline-logos/G3.png',
    price: '1.230',
    outbound: {
      day: '20/JAN',
      weekName: 'DOM',
      departureTime: '16:30',
      arrivalTime: '18:30',
      duretion: '2,5h',
    },
    back: {
      day: '22/JAN',
      weekName: 'TER',
      departureTime: '13:30',
      arrivalTime: '15:30',
      duretion: '2h',
    },
    departureAirport: 'FLN',
    arrivalAirport: 'GRU',
    id: '33232',
  },
];
